add Error callback to transcribe Method
CatalystCode/SpeechToText-WebSockets-Java pull request #6
Opened 2018-05-03 08:15 UTC by drummer3333

If errors occur while processing the data or the connection has problems, they where logged but not available the the API. I added Consumer for all occured Exceptions.

2018-05-03 12:50 UTC, imkrmgn requested changes
Hi @drummer3333 .

I commented because I was concerned about your change.
I am happy to think about my opinion.

2018-05-03 12:50 UTC, imkrmgn commented on src/main/java/com/github/catalystcode/fortis/speechtotext/lifecycle/MessageReceiver.java
> +        } catch (Exception e) {
It's easier to catch in `NvMessageReceiver#onTextMessage` than to catch here. And there is little modiftion.

2018-05-07 18:35 UTC, c-w commented
@drummer3333 Thanks for your pull request! Much appreciated. Could you please take a look at the comment of @imkrmgn and also update your branch with the latest changes from master? Thanks!

2018-06-20 21:52 UTC, c-w commented
There's now an official [Java/Android SDK](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedjavaandroid) so I'm archiving this repository and closing the pull request. Please migrate to the official SDK. Thanks!

2018-06-20 21:52 UTC, closed without merging